os: linux
sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - nightly
  - pypy3
env: TOXENV=py,coveralls

matrix:
  include:
    - env: TOXENV=stylecheck,docs-html
    - python: "2.7"
      env: TOXENV=py27,coveralls
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
